### ISSUE TITLE
Error: only one instance of babel-polyfill is allowed

### ISSUE THREAD

**Issue by hackape** [ealush/emoji-picker#2]
Apparently I use babel-polyfill in my own project too. Yet I don't find your config in webpack.config.js, how do i unuse it?

**Comment by hackape** [comment]
Oh I found it, it's imported in `index.js`. 

But I'll leave this issue open, since it is a problem I believe others will very likely encounter.

**Comment by ealush** [comment]
Thank you for the comment. This makes sense. I have updated `.babelrc` to use `babel-transform-runtime`. Can you please confirm that the error is not present anymore?

**Comment by noahjohn9259** [comment]
I am experiencing the same issue.

**Comment by ealush** [comment]
hey, @noahjohn9259  I pushed your fix. Does et work on your end now?
