### ISSUE TITLE
css not working properly

### ISSUE THREAD

**Issue by IshmeetSingh06** [ealush/emoji-picker#284]
Whenever i try to render the EmojiPicker anywhere instead of App.js it comes up with messed up css here are few screenshots regarding this:
![image](https://user-images.githubusercontent.com/76062864/196056048-3a57f6fb-48d7-467a-a806-ae64b7c33580.png)
here you can see the categories are coming up in pairs of two not singularly like in the demo
now if i render this in app.js using same configuration it comes up like this:
![image](https://user-images.githubusercontent.com/76062864/196056208-3bcb2910-ff7c-444f-928b-5dcdb59d0746.png)

**Comment by 00ricardo** [comment]
Hello, I spent lot of time overriding the css for the my particular picker but its possible though.

![image](https://user-images.githubusercontent.com/61938096/196065083-1ee94d1e-abb2-4a99-909f-87679a9ee905.png)

Try to override it with a CSS file and not with inline CSS. Make sure to set !important flag for each property. 

A dummy example:
![image](https://user-images.githubusercontent.com/61938096/196065307-889730ee-f635-47f1-8a48-7e6f409d5c50.png)

**Comment by 00ricardo** [comment]
Can you please confirm whether you have multiple picker instances? It looks like the picker is rendering all the elements twice. The skin tool is more large because they're maybe more than one? I'm just guessing what could it be.

If you feel comfortable sharing you code, feel free to it. Maybe its easier to help you.

**Comment by amatviychuk** [comment]
oh, sorry, i find the solution quickly — i have button element styling, which causes additional padding on all buttons in the project, including Emoji Picker. So, i've just remove it, and everything works fine. Thank you!
